"""empty message

Revision ID: 2914607e93e9
Revises: 
Create Date: 2019-09-25 21:12:18.670678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2914607e93e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disposition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dispositionname', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dispositionname')
    )
    op.create_table('store',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('storename', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storename')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calltype', sa.String(length=80), nullable=True),
    sa.Column('contacttype', sa.String(length=80), nullable=True),
    sa.Column('clientname', sa.Text(), nullable=False),
    sa.Column('datecreated', sa.Text(), nullable=False),
    sa.Column('disposition_id', sa.Integer(), nullable=True),
    sa.Column('mobileno', sa.Text(), nullable=False),
    sa.Column('questionsubtype', sa.Text(), nullable=False),
    sa.Column('questiontype', sa.Text(), nullable=False),
    sa.Column('sourcename', sa.Text(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('ticketid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['disposition_id'], ['disposition.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('store')
    op.drop_table('disposition')
    # ### end Alembic commands ###
